#version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html  # Mapea la carpeta local ./backend a /var/www/html en el contenedor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=integrando-db
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      
    depends_on:
      - db
    networks:
      - app-network
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000" # Comando para ejecutar Laravel
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: integrando-db
      
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge  # Network para conectar los servicios

volumes:
  mysql_data: {}  # Volumen para persistir los datos
